apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploypl
  labels:
    app: autodeploypl
  namespace: namespace-workflow-1700151092249
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploypl
  template:
    metadata:
      labels:
        app: autodeploypl
    spec:
      containers:
        - name: autodeploypl
          image: acrworkflow1700151092249.azurecr.io/image-workflow-1700151092249:latest
          ports:
            - containerPort: 5000
