apiVersion: v1
kind: Service
metadata:
  name: autodeploypl
  namespace: namespace-workflow-1700151092249
spec:
  type: LoadBalancer
  selector:
    app: autodeploypl
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
